apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver2
  template:
    metadata:
      labels:
        app: echoserver2
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.4
          imagePullPolicy: Always
          name: echoserver
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver2
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echoserver2
